### ISSUE TITLE
Add bad espace with @media keyword

### ISSUE THREAD

**Issue by tom-dr** [jonkemp/gulp-cssbeautify#14]
With code
```css
@supports not (inset: 10px) {
  .articles-wrapper.grid {
    margin: 0 0 5rem 0;
  }

  @media screen and (min-width: 750px) {
    .articles-wrapper.grid {
      margin-bottom: 7rem;
    }
  }
}
```
Be beautifyed like this
```css
@supports not (inset: 10px) {
    .articles-wrapper.grid {
        margin: 0 0 5rem 0;
    }
  @    media screen and (min-width: 750px) {
        .articles-wrapper.grid {
      margin-bottom: 7rem;
    }
}
}
```
